<p style="color:limegreen;">Brand: <b>
        <?php
        /**
         * @var Codilar\Attribute\Block\Attribute $block
         **/
        $currentProduct = $block->getCurrentProduct();
//        echo $currentProduct->getAttributeText('brand');
        ?><a href="<?php echo $block->getBrandUrl() . 'id/' . $block->getAttributeId() ?>"> <?php echo $currentProduct->getAttributeText('brand') ?> </a>
