<?php
/* @var \Starlabs\Attribute\Block\ProductList $block */
?>

<h3 style="color: green">


    <?php

    $items = $block->getText();
    if (count($items) > 0): ?>
    <table>
        <tr>
            <th><?php echo __('Id') ?></th>
            <th><?php echo __('Brand Name') ?></th>
        </tr>
        <?php foreach ($items as $item): ?>
            <tr>
                <?php if($item->getIsActive()==1):?>
                <td><?php echo $item->getBrandId()?></td>
                <td><a href="<?php echo $block->getBrandUrl(). 'id/' . $item->getBrandId() ?>"><?php echo $item->getName()?></a></td>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?>
        </thead>
    </table>
    <?php endif; ?>
    </div>
    ?>
</h3>




